language: ruby

addons:
  apt_packages:
    - pandoc

before_install:
  - gem install bundler

install:
  - bundle install
  
script:
  - jekyll build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: _site
  on:
    branch: master