language: ruby
sudo: true

addons:
  apt_packages:
    - graphviz

before_install:
  - wget https://github.com/jgm/pandoc/releases/download/2.7/pandoc-2.7-1-amd64.deb
  - sudo dpkg -i pandoc-2.7-1-amd64.deb
  - gem install bundler

install:
  - bundle install
  
script:
  - jekyll build --verbose --trace

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: _site
  on:
    branch: master